"""initial schema

Revision ID: 64c765483eec
Revises: 
Create Date: 2026-08-11 00:15:33.254561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c765483eec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idea_vault',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('content_type', sa.Enum('NEWS', 'BREAKING_NEWS', 'LONG_FORM', 'SHORT', 'PRODUCT_REVIEW', 'UNBOXING', 'PRODUCT_FEATURES', 'PRODUCT_COMPARISON', 'BUYING_GUIDE', 'EXPLAINER', 'RUMOR_LEAK', 'SOFTWARE_OS', 'AI_NEWS', name='contenttype'), nullable=True),
    sa.Column('priority', sa.Enum('BREAKING', 'HIGH_DEMAND', 'PRODUCT_LAUNCH', 'TRENDING', 'EVERGREEN', 'LOW_PRIORITY', name='priority'), nullable=True),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('suggested_title', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('content_type', sa.Enum('NEWS', 'BREAKING_NEWS', 'LONG_FORM', 'SHORT', 'PRODUCT_REVIEW', 'UNBOXING', 'PRODUCT_FEATURES', 'PRODUCT_COMPARISON', 'BUYING_GUIDE', 'EXPLAINER', 'RUMOR_LEAK', 'SOFTWARE_OS', 'AI_NEWS', name='contenttype'), nullable=False),
    sa.Column('duration_target_seconds', sa.Integer(), nullable=True),
    sa.Column('target_audience', sa.String(), nullable=True),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('user_instructions', sa.Text(), nullable=True),
    sa.Column('source_urls', sa.JSON(), nullable=True),
    sa.Column('product_info', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Enum('BREAKING', 'HIGH_DEMAND', 'PRODUCT_LAUNCH', 'TRENDING', 'EVERGREEN', 'LOW_PRIORITY', name='priority'), nullable=True),
    sa.Column('pipeline_mode', sa.Enum('AUTO', 'REVIEW', name='pipelinemode'), nullable=True),
    sa.Column('current_stage', sa.Enum('AV', 'RESEARCH', 'FACT_CHECK', 'SCRIPT', 'VOICE', 'VISUALS', 'COPYRIGHT', 'THUMBNAIL', 'PUBLISH', name='stage'), nullable=True),
    sa.Column('pipeline_state', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'NEEDS_REVIEW', 'BLOCKED', 'READY_TO_PUBLISH', 'PUBLISHED', 'DO_NOT_PUBLISH', 'REJECTED', name='pipelinestate'), nullable=True),
    sa.Column('freshness_score', sa.Float(), nullable=True),
    sa.Column('overall_quality_score', sa.Float(), nullable=True),
    sa.Column('scheduled_publish_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_videos_per_day', sa.Integer(), nullable=True),
    sa.Column('shorts_per_day', sa.Integer(), nullable=True),
    sa.Column('shorts_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('publishing_window_start', sa.String(), nullable=True),
    sa.Column('publishing_window_end', sa.String(), nullable=True),
    sa.Column('weekday_overrides', sa.JSON(), nullable=True),
    sa.Column('weekend_overrides', sa.JSON(), nullable=True),
    sa.Column('quality_threshold', sa.Float(), nullable=True),
    sa.Column('max_daily_output', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('AV', 'RESEARCH', 'FACT_CHECK', 'SCRIPT', 'VOICE', 'VISUALS', 'COPYRIGHT', 'THUMBNAIL', 'PUBLISH', name='stage'), nullable=False),
    sa.Column('action', sa.Enum('APPROVE', 'EDIT', 'REGENERATE', 'SEND_BACK', 'REJECT', name='approvalaction'), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('source_tier', sa.Enum('OFFICIAL', 'COMPANY', 'PRODUCT_PAGE', 'REGULATORY', 'DEV_DOCS', 'REPUTABLE_PRESS', 'SPECIALIST_PRESS', 'COMMUNITY', name='sourcetier'), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('AV', 'RESEARCH', 'FACT_CHECK', 'SCRIPT', 'VOICE', 'VISUALS', 'COPYRIGHT', 'THUMBNAIL', 'PUBLISH', name='stage'), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'NEEDS_REVIEW', name='stagerunstatus'), nullable=True),
    sa.Column('input_snapshot', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('stage_run_id', sa.Integer(), nullable=True),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('url_or_path', sa.String(), nullable=True),
    sa.Column('copyright_status', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='copyrightrisk'), nullable=True),
    sa.Column('copyright_notes', sa.Text(), nullable=True),
    sa.Column('timestamp_in_video', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['stage_run_id'], ['stage_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('stage_run_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(), nullable=True),
    sa.Column('verification_status', sa.Enum('VERIFIED', 'PARTIALLY_VERIFIED', 'REPORTED', 'RUMOR', 'CONTRADICTED', 'UNSUPPORTED', 'FALSE', name='verificationstatus'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_ids', sa.JSON(), nullable=True),
    sa.Column('fact_checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['stage_run_id'], ['stage_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_gate_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('stage_run_id', sa.Integer(), nullable=True),
    sa.Column('newsworthiness', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('research', sa.Float(), nullable=True),
    sa.Column('originality', sa.Float(), nullable=True),
    sa.Column('script', sa.Float(), nullable=True),
    sa.Column('voice', sa.Float(), nullable=True),
    sa.Column('visuals', sa.Float(), nullable=True),
    sa.Column('copyright', sa.Float(), nullable=True),
    sa.Column('thumbnail', sa.Float(), nullable=True),
    sa.Column('title', sa.Float(), nullable=True),
    sa.Column('viewer_value', sa.Float(), nullable=True),
    sa.Column('freshness', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['stage_run_id'], ['stage_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quality_gate_results')
    op.drop_table('claims')
    op.drop_table('assets')
    op.drop_table('stage_runs')
    op.drop_table('sources')
    op.drop_table('approval_events')
    op.drop_table('schedule_config')
    op.drop_table('projects')
    op.drop_table('idea_vault')
    # ### end Alembic commands ###
