"""scheduler lock table

Revision ID: 7a8c2862e1c5
Revises: f9c354e02a13
Create Date: 2026-08-13 18:45:48.932915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a8c2862e1c5'
down_revision: Union[str, Sequence[str], None] = 'f9c354e02a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_lock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holder', sa.String(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduler_lock')
    # ### end Alembic commands ###
