"""asset upload fields

Revision ID: f9c354e02a13
Revises: 64c765483eec
Create Date: 2026-08-13 06:16:27.580840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c354e02a13'
down_revision: Union[str, Sequence[str], None] = '64c765483eec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('is_user_upload', sa.Boolean(), nullable=True))
    op.add_column('assets', sa.Column('original_filename', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'uploaded_at')
    op.drop_column('assets', 'original_filename')
    op.drop_column('assets', 'is_user_upload')
    # ### end Alembic commands ###
